// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QQiOBrzNnhiIM9bZGW4vxhgjET7utPk',
    appId: '1:533477848659:web:3c227b4d4395ebac1c78a6',
    messagingSenderId: '533477848659',
    projectId: 'ecommerce-app-a2523',
    authDomain: 'ecommerce-app-a2523.firebaseapp.com',
    storageBucket: 'ecommerce-app-a2523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJbGd5X8c1maMPqd2SReqgcnFbbCUKXto',
    appId: '1:533477848659:android:c7bd6c61594a3cba1c78a6',
    messagingSenderId: '533477848659',
    projectId: 'ecommerce-app-a2523',
    storageBucket: 'ecommerce-app-a2523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNr-Pbacrd_1ZONiDj4gcBeIH9r04B6Y',
    appId: '1:533477848659:ios:214aa071705b20531c78a6',
    messagingSenderId: '533477848659',
    projectId: 'ecommerce-app-a2523',
    storageBucket: 'ecommerce-app-a2523.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNr-Pbacrd_1ZONiDj4gcBeIH9r04B6Y',
    appId: '1:533477848659:ios:214aa071705b20531c78a6',
    messagingSenderId: '533477848659',
    projectId: 'ecommerce-app-a2523',
    storageBucket: 'ecommerce-app-a2523.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3QQiOBrzNnhiIM9bZGW4vxhgjET7utPk',
    appId: '1:533477848659:web:4676838cd22f94a81c78a6',
    messagingSenderId: '533477848659',
    projectId: 'ecommerce-app-a2523',
    authDomain: 'ecommerce-app-a2523.firebaseapp.com',
    storageBucket: 'ecommerce-app-a2523.firebasestorage.app',
  );
}
